# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from . import icons_rc


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(550, 405)
        MainWindow.setMinimumSize(QtCore.QSize(550, 405))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.main = QtWidgets.QWidget(MainWindow)
        self.main.setMinimumSize(QtCore.QSize(550, 405))
        self.main.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.main.setStyleSheet("#main {\n"
                                "    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(244, 244, 253, 255), stop:1 rgba(223, 221, 243, 255))\n"
                                "}\n"
                                "")
        self.main.setObjectName("main")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.main)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.header = QtWidgets.QFrame(self.main)
        self.header.setMinimumSize(QtCore.QSize(0, 60))
        self.header.setMaximumSize(QtCore.QSize(16777215, 60))
        self.header.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header.setObjectName("header")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.header)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.logo = QtWidgets.QFrame(self.header)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.logo.setFont(font)
        self.logo.setStyleSheet("margin-left: 6px")
        self.logo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.logo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.logo.setObjectName("logo")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.logo)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.logo_text = QtWidgets.QLabel(self.logo)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(62)
        self.logo_text.setFont(font)
        self.logo_text.setStyleSheet("line-height: 141.6%;\n"
                                     "letter-spacing: 0.175em;\n"
                                     "text-transform: capitalize;\n"
                                     "font-weight: 500;")
        self.logo_text.setObjectName("logo_text")
        self.horizontalLayout_3.addWidget(self.logo_text)
        self.horizontalLayout_2.addWidget(self.logo, 0, QtCore.Qt.AlignBottom)
        self.info = QtWidgets.QFrame(self.header)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.info.sizePolicy().hasHeightForWidth())
        self.info.setSizePolicy(sizePolicy)
        self.info.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.info.setFrameShadow(QtWidgets.QFrame.Raised)
        self.info.setObjectName("info")
        self.horizontalLayout_2.addWidget(self.info)
        self.verticalLayout.addWidget(self.header)
        self.body = QtWidgets.QFrame(self.main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.body.sizePolicy().hasHeightForWidth())
        self.body.setSizePolicy(sizePolicy)
        self.body.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.body.setFrameShadow(QtWidgets.QFrame.Raised)
        self.body.setObjectName("body")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.body)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sideBar = QtWidgets.QFrame(self.body)
        self.sideBar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sideBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sideBar.setObjectName("sideBar")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.sideBar)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(0, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.btnContainer = QtWidgets.QFrame(self.sideBar)
        font = QtGui.QFont()
        font.setPointSize(5)
        self.btnContainer.setFont(font)
        self.btnContainer.setStyleSheet("#btnContainer {\n"
                                        "    margin-left: 15\n"
                                        "}\n"
                                        "\n"
                                        "#spleetBtn, #lyricBtn, #mixBtn {\n"
                                        "    text-align: left;\n"
                                        "    background-color: transparent;\n"
                                        "}")
        self.btnContainer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.btnContainer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.btnContainer.setObjectName("btnContainer")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.btnContainer)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.spleetBtn = QtWidgets.QPushButton(self.btnContainer)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(6)
        self.spleetBtn.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/sliders.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.spleetBtn.setIcon(icon)
        self.spleetBtn.setIconSize(QtCore.QSize(9, 9))
        self.spleetBtn.setObjectName("spleetBtn")
        self.verticalLayout_2.addWidget(self.spleetBtn)
        self.mixBtn = QtWidgets.QPushButton(self.btnContainer)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(6)
        self.mixBtn.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/link.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mixBtn.setIcon(icon1)
        self.mixBtn.setIconSize(QtCore.QSize(9, 9))
        self.mixBtn.setObjectName("mixBtn")
        self.verticalLayout_2.addWidget(self.mixBtn)
        self.verticalLayout_3.addWidget(self.btnContainer)
        self.horizontalLayout.addWidget(self.sideBar, 0, QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.mainContent = QtWidgets.QFrame(self.body)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainContent.sizePolicy().hasHeightForWidth())
        self.mainContent.setSizePolicy(sizePolicy)
        self.mainContent.setStyleSheet("QStackedWidget>QWidget {\n"
                                       "    background: transparent;\n"
                                       "}\n"
                                       "\n"
                                       "QStackedWidget>* {\n"
                                       "}")
        self.mainContent.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainContent.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainContent.setObjectName("mainContent")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.mainContent)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.stackedWidget = QtWidgets.QStackedWidget(self.mainContent)
        self.stackedWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.spleet = QtWidgets.QWidget()
        self.spleet.setObjectName("spleet")
        self.frame = QtWidgets.QFrame(self.spleet)
        self.frame.setGeometry(QtCore.QRect(0, 0, 291, 339))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setStyleSheet("#nextBtnSpleet, #playBtnSpleet, #prevBtnSpleet {\n"
                                 "    background: transparent\n"
                                 "}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setGeometry(QtCore.QRect(10, 190, 270, 147))
        self.frame_4.setStyleSheet("QSlider::groove:horizontal {\n"
                                   "    height: 2px; /* the groove expands to the size of the slider by default. by giving it a height, it has a fixed size */\n"
                                   "    background: #E85353;\n"
                                   "    margin: 2px 0;\n"
                                   "}\n"
                                   "\n"
                                   "QSlider::handle:horizontal {\n"
                                   "    background: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.194, fx:0.5, fy:0.5, stop:0 rgba(232, 83, 83, 255), stop:0.479904 rgba(232, 83, 83, 255), stop:0.522685 rgba(241, 230, 106, 255), stop:1 rgba(241, 230, 106, 255));\n"
                                   "    border: 1px solid #FFBE0F;\n"
                                   "    width: 6px;\n"
                                   "    margin: -3px 0; /* handle is placed by default on the contents rect of the groove. Expand outside the groove */\n"
                                   "    border-radius: 4px;\n"
                                   "}\n"
                                   "\n"
                                   "QPushButton {\n"
                                   "    background: transparent;\n"
                                   "    border-radius: 9;\n"
                                   "}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(10)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.frame_4)
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/images/images/vocal.png"))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.sliderVocalSpleet = QtWidgets.QSlider(self.frame_4)
        self.sliderVocalSpleet.setEnabled(True)
        self.sliderVocalSpleet.setMinimumSize(QtCore.QSize(0, 0))
        self.sliderVocalSpleet.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.sliderVocalSpleet.setTracking(True)
        self.sliderVocalSpleet.setOrientation(QtCore.Qt.Horizontal)
        self.sliderVocalSpleet.setObjectName("sliderVocalSpleet")
        self.horizontalLayout_5.addWidget(self.sliderVocalSpleet)
        self.downVocalSpleet = QtWidgets.QPushButton(self.frame_4)
        self.downVocalSpleet.setMinimumSize(QtCore.QSize(18, 18))
        self.downVocalSpleet.setMaximumSize(QtCore.QSize(18, 18))
        self.downVocalSpleet.setStyleSheet("")
        self.downVocalSpleet.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/download.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.downVocalSpleet.setIcon(icon2)
        self.downVocalSpleet.setIconSize(QtCore.QSize(12, 12))
        self.downVocalSpleet.setObjectName("downVocalSpleet")
        self.horizontalLayout_5.addWidget(self.downVocalSpleet)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(10)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_8 = QtWidgets.QLabel(self.frame_4)
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap(":/images/images/bass.png"))
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.label_8)
        self.sliderBassSpleet = QtWidgets.QSlider(self.frame_4)
        self.sliderBassSpleet.setOrientation(QtCore.Qt.Horizontal)
        self.sliderBassSpleet.setObjectName("sliderBassSpleet")
        self.horizontalLayout_8.addWidget(self.sliderBassSpleet)
        self.downBassSpleet = QtWidgets.QPushButton(self.frame_4)
        self.downBassSpleet.setMinimumSize(QtCore.QSize(18, 18))
        self.downBassSpleet.setMaximumSize(QtCore.QSize(18, 18))
        self.downBassSpleet.setText("")
        self.downBassSpleet.setIcon(icon2)
        self.downBassSpleet.setIconSize(QtCore.QSize(12, 12))
        self.downBassSpleet.setObjectName("downBassSpleet")
        self.horizontalLayout_8.addWidget(self.downBassSpleet)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(10)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.frame_4)
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap(":/images/images/piano.png"))
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.sliderPianoSpleet = QtWidgets.QSlider(self.frame_4)
        self.sliderPianoSpleet.setOrientation(QtCore.Qt.Horizontal)
        self.sliderPianoSpleet.setObjectName("sliderPianoSpleet")
        self.horizontalLayout_7.addWidget(self.sliderPianoSpleet)
        self.downPianoSpleet = QtWidgets.QPushButton(self.frame_4)
        self.downPianoSpleet.setMaximumSize(QtCore.QSize(18, 18))
        self.downPianoSpleet.setText("")
        self.downPianoSpleet.setIcon(icon2)
        self.downPianoSpleet.setIconSize(QtCore.QSize(12, 12))
        self.downPianoSpleet.setObjectName("downPianoSpleet")
        self.horizontalLayout_7.addWidget(self.downPianoSpleet)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(10)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.frame_4)
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(":/images/images/drum.png"))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.sliderDrumSpleet = QtWidgets.QSlider(self.frame_4)
        self.sliderDrumSpleet.setOrientation(QtCore.Qt.Horizontal)
        self.sliderDrumSpleet.setObjectName("sliderDrumSpleet")
        self.horizontalLayout_6.addWidget(self.sliderDrumSpleet)
        self.downDrumSpleet = QtWidgets.QPushButton(self.frame_4)
        self.downDrumSpleet.setMaximumSize(QtCore.QSize(18, 18))
        self.downDrumSpleet.setText("")
        self.downDrumSpleet.setIcon(icon2)
        self.downDrumSpleet.setIconSize(QtCore.QSize(12, 12))
        self.downDrumSpleet.setObjectName("downDrumSpleet")
        self.horizontalLayout_6.addWidget(self.downDrumSpleet)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(10)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_5 = QtWidgets.QLabel(self.frame_4)
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(":/images/images/other.png"))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_9.addWidget(self.label_5)
        self.sliderOtherSpleet = QtWidgets.QSlider(self.frame_4)
        self.sliderOtherSpleet.setOrientation(QtCore.Qt.Horizontal)
        self.sliderOtherSpleet.setObjectName("sliderOtherSpleet")
        self.horizontalLayout_9.addWidget(self.sliderOtherSpleet)
        self.downOtherSpleet = QtWidgets.QPushButton(self.frame_4)
        self.downOtherSpleet.setMaximumSize(QtCore.QSize(18, 18))
        self.downOtherSpleet.setText("")
        self.downOtherSpleet.setIcon(icon2)
        self.downOtherSpleet.setIconSize(QtCore.QSize(12, 12))
        self.downOtherSpleet.setObjectName("downOtherSpleet")
        self.horizontalLayout_9.addWidget(self.downOtherSpleet)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        self.speedBtn = QtWidgets.QPushButton(self.frame)
        self.speedBtn.setGeometry(QtCore.QRect(177, 41, 30, 30))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.speedBtn.setFont(font)
        self.speedBtn.setStyleSheet("border-radius: 15;\n"
                                    "background-color: transparent;\n"
                                    "border: 2px solid #9C9BBB;\n"
                                    "color: #9C9BBB;")
        self.speedBtn.setObjectName("speedBtn")
        self.sliderSongPlayingSpleet = QtWidgets.QSlider(self.frame)
        self.sliderSongPlayingSpleet.setGeometry(QtCore.QRect(10, 26, 260, 16))
        self.sliderSongPlayingSpleet.setStyleSheet("QSlider::groove:horizontal {\n"
                                                   "    height: 2px; /* the groove expands to the size of the slider by default. by giving it a height, it has a fixed size */\n"
                                                   "    background: #E85353;\n"
                                                   "    margin: 2px 0;\n"
                                                   "}\n"
                                                   "\n"
                                                   "QSlider::handle:horizontal {\n"
                                                   "    background: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.194, fx:0.5, fy:0.5, stop:0 rgba(232, 83, 83, 255), stop:0.479904 rgba(232, 83, 83, 255), stop:0.522685 rgba(241, 230, 106, 255), stop:1 rgba(241, 230, 106, 255));\n"
                                                   "    border: 1px solid #FFBE0F;\n"
                                                   "    width: 6px;\n"
                                                   "    margin: -3px 0; /* handle is placed by default on the contents rect of the groove. Expand outside the groove */\n"
                                                   "    border-radius: 4px;\n"
                                                   "}")
        self.sliderSongPlayingSpleet.setOrientation(QtCore.Qt.Horizontal)
        self.sliderSongPlayingSpleet.setObjectName("sliderSongPlayingSpleet")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.frame)
        self.scrollArea_2.setGeometry(QtCore.QRect(10, 79, 270, 100))
        self.scrollArea_2.setStyleSheet("border: none;\n"
                                        "background: #9C9BBB;\n"
                                        "border: none;\n"
                                        "color: white;\n"
                                        "border-radius: 12px;")
        self.scrollArea_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.lyricArea = QtWidgets.QWidget()
        self.lyricArea.setGeometry(QtCore.QRect(0, 0, 270, 1000))
        self.lyricArea.setMinimumSize(QtCore.QSize(0, 1000))
        self.lyricArea.setStyleSheet("background: #9C9BBB;\n"
                                     "border: none;\n"
                                     "color: white;\n"
                                     "border-radius: 12px;")
        self.lyricArea.setObjectName("lyricArea")
        self.lyricLabel = QtWidgets.QLabel(self.lyricArea)
        self.lyricLabel.setGeometry(QtCore.QRect(0, 0, 270, 100))
        self.lyricLabel.setStyleSheet("padding: 6 8;\n"
                                      "border-radius: 12px;\n"
                                      "")
        self.lyricLabel.setWordWrap(True)
        self.lyricLabel.setObjectName("lyricLabel")
        self.scrollArea_2.setWidget(self.lyricArea)
        self.nameSongPlayingSpleet = QtWidgets.QLabel(self.frame)
        self.nameSongPlayingSpleet.setGeometry(QtCore.QRect(10, 0, 270, 23))
        self.nameSongPlayingSpleet.setMinimumSize(QtCore.QSize(270, 0))
        self.nameSongPlayingSpleet.setMaximumSize(QtCore.QSize(270, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.nameSongPlayingSpleet.setFont(font)
        self.nameSongPlayingSpleet.setLineWidth(1)
        self.nameSongPlayingSpleet.setWordWrap(False)
        self.nameSongPlayingSpleet.setObjectName("nameSongPlayingSpleet")
        self.widget = QtWidgets.QWidget(self.frame)
        self.widget.setGeometry(QtCore.QRect(61, 43, 98, 26))
        self.widget.setObjectName("widget")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.prevBtnSpleet = QtWidgets.QPushButton(self.widget)
        self.prevBtnSpleet.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/skip-back.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.prevBtnSpleet.setIcon(icon3)
        self.prevBtnSpleet.setObjectName("prevBtnSpleet")
        self.horizontalLayout_11.addWidget(self.prevBtnSpleet)
        self.playBtnSpleet = QtWidgets.QPushButton(self.widget)
        self.playBtnSpleet.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/play.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.playBtnSpleet.setIcon(icon4)
        self.playBtnSpleet.setObjectName("playBtnSpleet")
        self.horizontalLayout_11.addWidget(self.playBtnSpleet)
        self.nextBtnSpleet = QtWidgets.QPushButton(self.widget)
        self.nextBtnSpleet.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/skip-forward.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.nextBtnSpleet.setIcon(icon5)
        self.nextBtnSpleet.setObjectName("nextBtnSpleet")
        self.horizontalLayout_11.addWidget(self.nextBtnSpleet)
        self.frame_3 = QtWidgets.QFrame(self.spleet)
        self.frame_3.setGeometry(QtCore.QRect(290, 0, 160, 341))
        self.frame_3.setMinimumSize(QtCore.QSize(160, 0))
        self.frame_3.setMaximumSize(QtCore.QSize(160, 16777215))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_7.setContentsMargins(0, 15, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        self.frame_5.setMaximumSize(QtCore.QSize(160, 16777215))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_9 = QtWidgets.QLabel(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(62)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("font-weight: 500")
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_10.addWidget(self.label_9)
        self.addBtnSpleet = QtWidgets.QPushButton(self.frame_5)
        self.addBtnSpleet.setStyleSheet("background: transparent")
        self.addBtnSpleet.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/images/images/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addBtnSpleet.setIcon(icon6)
        self.addBtnSpleet.setObjectName("addBtnSpleet")
        self.horizontalLayout_10.addWidget(self.addBtnSpleet, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_7.addWidget(self.frame_5, 0, QtCore.Qt.AlignTop)
        self.scrollArea_4 = QtWidgets.QScrollArea(self.frame_3)
        self.scrollArea_4.setStyleSheet("background: transparent;\n"
                                        "border: none;")
        self.scrollArea_4.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollArea_4.setObjectName("scrollArea_4")
        self.listSpleet = QtWidgets.QWidget()
        self.listSpleet.setGeometry(QtCore.QRect(0, 0, 158, 1000))
        self.listSpleet.setMinimumSize(QtCore.QSize(0, 1000))
        self.listSpleet.setObjectName("listSpleet")
        self.frame_13 = QtWidgets.QFrame(self.listSpleet)
        self.frame_13.setGeometry(QtCore.QRect(0, 0, 150, 41))
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.nameSongListSpleet = QtWidgets.QLabel(self.frame_13)
        self.nameSongListSpleet.setGeometry(QtCore.QRect(40, 8, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.nameSongListSpleet.setFont(font)
        self.nameSongListSpleet.setObjectName("nameSongListSpleet")
        self.authorSongListSpleet = QtWidgets.QLabel(self.frame_13)
        self.authorSongListSpleet.setGeometry(QtCore.QRect(40, 20, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(6)
        self.authorSongListSpleet.setFont(font)
        self.authorSongListSpleet.setStyleSheet("color: #9C9BBB")
        self.authorSongListSpleet.setObjectName("authorSongListSpleet")
        self.songListSpleet = QtWidgets.QPushButton(self.frame_13)
        self.songListSpleet.setGeometry(QtCore.QRect(0, 0, 140, 41))
        self.songListSpleet.setMinimumSize(QtCore.QSize(140, 0))
        self.songListSpleet.setMaximumSize(QtCore.QSize(140, 16777215))
        self.songListSpleet.setStyleSheet("background-color: transparent;\n"
                                          "border: 1px solid #9C9BBB;\n"
                                          "border-radius: 9;")
        self.songListSpleet.setText("")
        self.songListSpleet.setObjectName("songListSpleet")
        self.downSongSpleet = QtWidgets.QPushButton(self.frame_13)
        self.downSongSpleet.setGeometry(QtCore.QRect(113, 10, 22, 22))
        self.downSongSpleet.setStyleSheet("background: transparent;\n"
                                          "border-radius: 11;")
        self.downSongSpleet.setText("")
        self.downSongSpleet.setIcon(icon2)
        self.downSongSpleet.setIconSize(QtCore.QSize(12, 12))
        self.downSongSpleet.setObjectName("downSongSpleet")
        self.label_18 = QtWidgets.QLabel(self.frame_13)
        self.label_18.setGeometry(QtCore.QRect(5, 5, 30, 30))
        self.label_18.setText("")
        self.label_18.setPixmap(QtGui.QPixmap(":/images/images/music.png"))
        self.label_18.setObjectName("label_18")
        self.scrollArea_4.setWidget(self.listSpleet)
        self.verticalLayout_7.addWidget(self.scrollArea_4)
        self.stackedWidget.addWidget(self.spleet)
        self.mix = QtWidgets.QWidget()
        self.mix.setObjectName("mix")
        self.frame_46 = QtWidgets.QFrame(self.mix)
        self.frame_46.setGeometry(QtCore.QRect(0, 0, 291, 339))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_46.sizePolicy().hasHeightForWidth())
        self.frame_46.setSizePolicy(sizePolicy)
        self.frame_46.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_46.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_46.setObjectName("frame_46")
        self.label_104 = QtWidgets.QLabel(self.frame_46)
        self.label_104.setGeometry(QtCore.QRect(20, 10, 40, 40))
        self.label_104.setText("")
        self.label_104.setPixmap(QtGui.QPixmap(":/images/images/retro.png"))
        self.label_104.setObjectName("label_104")
        self.sliderSongPlayingMix = QtWidgets.QSlider(self.frame_46)
        self.sliderSongPlayingMix.setGeometry(QtCore.QRect(20, 60, 251, 16))
        self.sliderSongPlayingMix.setStyleSheet("QSlider::groove:horizontal {\n"
                                                "    height: 2px; /* the groove expands to the size of the slider by default. by giving it a height, it has a fixed size */\n"
                                                "    background: #E85353;\n"
                                                "    margin: 2px 0;\n"
                                                "}\n"
                                                "\n"
                                                "QSlider::handle:horizontal {\n"
                                                "    background: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.194, fx:0.5, fy:0.5, stop:0 rgba(232, 83, 83, 255), stop:0.479904 rgba(232, 83, 83, 255), stop:0.522685 rgba(241, 230, 106, 255), stop:1 rgba(241, 230, 106, 255));\n"
                                                "    border: 1px solid #FFBE0F;\n"
                                                "    width: 6px;\n"
                                                "    margin: -3px 0; /* handle is placed by default on the contents rect of the groove. Expand outside the groove */\n"
                                                "    border-radius: 4px;\n"
                                                "}")
        self.sliderSongPlayingMix.setOrientation(QtCore.Qt.Horizontal)
        self.sliderSongPlayingMix.setObjectName("sliderSongPlayingMix")
        self.scrollArea = QtWidgets.QScrollArea(self.frame_46)
        self.scrollArea.setGeometry(QtCore.QRect(20, 112, 251, 171))
        self.scrollArea.setStyleSheet("background: transparent;\n"
                                      "border: none;")
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 251, 1000))
        self.scrollAreaWidgetContents_2.setMinimumSize(QtCore.QSize(0, 1000))
        self.scrollAreaWidgetContents_2.setStyleSheet("QFrame {\n"
                                                      "    border: 1px solid #9C9BBB;\n"
                                                      "    border-radius: 12\n"
                                                      "}\n"
                                                      "\n"
                                                      "QLabel {\n"
                                                      "    border: none\n"
                                                      "}\n"
                                                      "\n"
                                                      "QSlider::groove:horizontal {\n"
                                                      "    height: 2px; /* the groove expands to the size of the slider by default. by giving it a height, it has a fixed size */\n"
                                                      "    background: #E85353;\n"
                                                      "    margin: 2px 0;\n"
                                                      "}\n"
                                                      "\n"
                                                      "QSlider::handle:horizontal {\n"
                                                      "    background: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.194, fx:0.5, fy:0.5, stop:0 rgba(232, 83, 83, 255), stop:0.479904 rgba(232, 83, 83, 255), stop:0.522685 rgba(241, 230, 106, 255), stop:1 rgba(241, 230, 106, 255));\n"
                                                      "    border: 1px solid #FFBE0F;\n"
                                                      "    width: 6px;\n"
                                                      "    margin: -3px 0; /* handle is placed by default on the contents rect of the groove. Expand outside the groove */\n"
                                                      "    border-radius: 4px;\n"
                                                      "}\n"
                                                      "\n"
                                                      "#mixMix {\n"
                                                      "    border: none\n"
                                                      "}")
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.mixMix = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.mixMix.setGeometry(QtCore.QRect(0, 0, 251, 45))
        self.mixMix.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mixMix.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mixMix.setObjectName("mixMix")
        self.widget1 = QtWidgets.QWidget(self.mixMix)
        self.widget1.setGeometry(QtCore.QRect(1, 1, 251, 43))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.frame_51 = QtWidgets.QFrame(self.widget1)
        self.frame_51.setMinimumSize(QtCore.QSize(110, 41))
        self.frame_51.setMaximumSize(QtCore.QSize(16777215, 41))
        self.frame_51.setStyleSheet("")
        self.frame_51.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_51.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_51.setObjectName("frame_51")
        self.label_105 = QtWidgets.QLabel(self.frame_51)
        self.label_105.setGeometry(QtCore.QRect(5, 0, 47, 41))
        self.label_105.setText("")
        self.label_105.setPixmap(QtGui.QPixmap(":/images/images/music.png"))
        self.label_105.setObjectName("label_105")
        self.nameSongEleMix = QtWidgets.QLabel(self.frame_51)
        self.nameSongEleMix.setGeometry(QtCore.QRect(40, 7, 47, 14))
        self.nameSongEleMix.setObjectName("nameSongEleMix")
        self.authorSongEleMix = QtWidgets.QLabel(self.frame_51)
        self.authorSongEleMix.setGeometry(QtCore.QRect(40, 20, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.authorSongEleMix.setFont(font)
        self.authorSongEleMix.setStyleSheet("color: #9c9bbb")
        self.authorSongEleMix.setObjectName("authorSongEleMix")
        self.horizontalLayout_12.addWidget(self.frame_51)
        self.sliderEleMix = QtWidgets.QSlider(self.widget1)
        self.sliderEleMix.setEnabled(True)
        self.sliderEleMix.setMinimumSize(QtCore.QSize(0, 0))
        self.sliderEleMix.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.sliderEleMix.setTracking(True)
        self.sliderEleMix.setOrientation(QtCore.Qt.Horizontal)
        self.sliderEleMix.setObjectName("sliderEleMix")
        self.horizontalLayout_12.addWidget(self.sliderEleMix)
        self.removeEleBtn = QtWidgets.QPushButton(self.widget1)
        self.removeEleBtn.setMinimumSize(QtCore.QSize(18, 18))
        self.removeEleBtn.setMaximumSize(QtCore.QSize(18, 18))
        self.removeEleBtn.setStyleSheet("")
        self.removeEleBtn.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/icons/minus.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.removeEleBtn.setIcon(icon7)
        self.removeEleBtn.setIconSize(QtCore.QSize(12, 12))
        self.removeEleBtn.setObjectName("removeEleBtn")
        self.horizontalLayout_12.addWidget(self.removeEleBtn)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.exportBtnMix = QtWidgets.QPushButton(self.frame_46)
        self.exportBtnMix.setGeometry(QtCore.QRect(200, 300, 75, 23))
        self.exportBtnMix.setStyleSheet("background-color: #FAF9FE;\n"
                                        "border: 0px;\n"
                                        "border-radius: 6;")
        self.exportBtnMix.setObjectName("exportBtnMix")
        self.nameSongPlayingMix = QtWidgets.QLabel(self.frame_46)
        self.nameSongPlayingMix.setGeometry(QtCore.QRect(65, 16, 200, 23))
        self.nameSongPlayingMix.setMinimumSize(QtCore.QSize(200, 0))
        self.nameSongPlayingMix.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.nameSongPlayingMix.setFont(font)
        self.nameSongPlayingMix.setLineWidth(1)
        self.nameSongPlayingMix.setWordWrap(False)
        self.nameSongPlayingMix.setObjectName("nameSongPlayingMix")
        self.playBtnMix = QtWidgets.QPushButton(self.frame_46)
        self.playBtnMix.setGeometry(QtCore.QRect(130, 78, 28, 24))
        self.playBtnMix.setStyleSheet("background: transparent")
        self.playBtnMix.setText("")
        self.playBtnMix.setIcon(icon4)
        self.playBtnMix.setObjectName("playBtnMix")
        self.frame_10 = QtWidgets.QFrame(self.mix)
        self.frame_10.setGeometry(QtCore.QRect(290, 0, 160, 341))
        self.frame_10.setMinimumSize(QtCore.QSize(160, 0))
        self.frame_10.setMaximumSize(QtCore.QSize(160, 16777215))
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_13.setContentsMargins(0, 15, 0, 0)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.frame_11 = QtWidgets.QFrame(self.frame_10)
        self.frame_11.setMaximumSize(QtCore.QSize(160, 16777215))
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_12 = QtWidgets.QLabel(self.frame_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(62)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("font-weight: 500")
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_15.addWidget(self.label_12)
        self.addBtnMix = QtWidgets.QPushButton(self.frame_11)
        self.addBtnMix.setStyleSheet("background: transparent")
        self.addBtnMix.setText("")
        self.addBtnMix.setIcon(icon6)
        self.addBtnMix.setObjectName("addBtnMix")
        self.horizontalLayout_15.addWidget(self.addBtnMix, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_13.addWidget(self.frame_11, 0, QtCore.Qt.AlignTop)
        self.scrollArea_3 = QtWidgets.QScrollArea(self.frame_10)
        self.scrollArea_3.setStyleSheet("background: transparent;\n"
                                        "border: none;")
        self.scrollArea_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.listMix = QtWidgets.QWidget()
        self.listMix.setGeometry(QtCore.QRect(0, 0, 158, 1000))
        self.listMix.setMinimumSize(QtCore.QSize(0, 1000))
        self.listMix.setStyleSheet("QComboBox QAbstractItemView {\n"
                                   "    background-color: white;\n"
                                   "    selection-background-color: blue;\n"
                                   "    color: white;\n"
                                   "}")
        self.listMix.setObjectName("listMix")
        self.frame_39 = QtWidgets.QFrame(self.listMix)
        self.frame_39.setGeometry(QtCore.QRect(0, 0, 140, 42))
        self.frame_39.setStyleSheet("")
        self.frame_39.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_39.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_39.setObjectName("frame_39")
        self.nameSongListMix = QtWidgets.QLabel(self.frame_39)
        self.nameSongListMix.setGeometry(QtCore.QRect(40, 8, 41, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.nameSongListMix.setFont(font)
        self.nameSongListMix.setObjectName("nameSongListMix")
        self.authorSongListMix = QtWidgets.QLabel(self.frame_39)
        self.authorSongListMix.setGeometry(QtCore.QRect(40, 20, 41, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(6)
        self.authorSongListMix.setFont(font)
        self.authorSongListMix.setStyleSheet("color: #9C9BBB")
        self.authorSongListMix.setObjectName("authorSongListMix")
        self.songListMix = QtWidgets.QPushButton(self.frame_39)
        self.songListMix.setGeometry(QtCore.QRect(0, 0, 140, 41))
        self.songListMix.setMinimumSize(QtCore.QSize(140, 0))
        self.songListMix.setMaximumSize(QtCore.QSize(140, 16777215))
        self.songListMix.setStyleSheet("background-color: transparent;\n"
                                       "border: 1px solid #9C9BBB;\n"
                                       "border-radius: 9;")
        self.songListMix.setText("")
        self.songListMix.setObjectName("songListMix")
        self.label_85 = QtWidgets.QLabel(self.frame_39)
        self.label_85.setGeometry(QtCore.QRect(5, 5, 30, 30))
        self.label_85.setText("")
        self.label_85.setPixmap(QtGui.QPixmap(":/images/images/music.png"))
        self.label_85.setObjectName("label_85")
        self.comboBoxListMix = QtWidgets.QComboBox(self.frame_39)
        self.comboBoxListMix.setGeometry(QtCore.QRect(85, 10, 55, 22))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.comboBoxListMix.setFont(font)
        self.comboBoxListMix.setStyleSheet("border: none;\n"
                                           "background-color: transparent;\n"
                                           "border-radius: 6px;")
        self.comboBoxListMix.setIconSize(QtCore.QSize(8, 8))
        self.comboBoxListMix.setObjectName("comboBoxListMix")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/icons/hash.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBoxListMix.addItem(icon8, "")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/images/images/vocal.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBoxListMix.addItem(icon9, "")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/images/images/bass.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBoxListMix.addItem(icon10, "")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/images/images/piano.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBoxListMix.addItem(icon11, "")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/images/images/drum.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBoxListMix.addItem(icon12, "")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/images/images/other.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBoxListMix.addItem(icon13, "")
        self.scrollArea_3.setWidget(self.listMix)
        self.verticalLayout_13.addWidget(self.scrollArea_3)
        self.stackedWidget.addWidget(self.mix)
        self.horizontalLayout_4.addWidget(self.stackedWidget)
        self.horizontalLayout.addWidget(self.mainContent)
        self.verticalLayout.addWidget(self.body)
        MainWindow.setCentralWidget(self.main)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.addFunction()
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.logo_text.setText(_translate("MainWindow", "Spleeter"))
        self.spleetBtn.setText(_translate("MainWindow", "Spleet"))
        self.mixBtn.setText(_translate("MainWindow", "Mix"))
        self.speedBtn.setText(_translate("MainWindow", "x1.0"))
        self.lyricLabel.setText(_translate("MainWindow",
                                           "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages,"))
        self.nameSongPlayingSpleet.setText(_translate("MainWindow", "Esther Howard"))
        self.label_9.setText(_translate("MainWindow", "List"))
        self.nameSongListSpleet.setText(_translate("MainWindow", "Esther Howard"))
        self.authorSongListSpleet.setText(_translate("MainWindow", "Guary"))
        self.nameSongEleMix.setText(_translate("MainWindow", "Vocal"))
        self.authorSongEleMix.setText(_translate("MainWindow", "Esther Howard"))
        self.exportBtnMix.setText(_translate("MainWindow", "Export"))
        self.nameSongPlayingMix.setText(_translate("MainWindow", "Esther Howard"))
        self.label_12.setText(_translate("MainWindow", "List"))
        self.nameSongListMix.setText(_translate("MainWindow", "Esther Howard"))
        self.authorSongListMix.setText(_translate("MainWindow", "Guary"))
        self.comboBoxListMix.setCurrentText(_translate("MainWindow", "None"))
        self.comboBoxListMix.setItemText(0, _translate("MainWindow", "None"))
        self.comboBoxListMix.setItemText(1, _translate("MainWindow", "Vocal"))
        self.comboBoxListMix.setItemText(2, _translate("MainWindow", "Bass"))
        self.comboBoxListMix.setItemText(3, _translate("MainWindow", "Piano"))
        self.comboBoxListMix.setItemText(4, _translate("MainWindow", "Drum"))
        self.comboBoxListMix.setItemText(5, _translate("MainWindow", "Other"))

    def addFunction(self):
        self.spleetBtn.clicked.connect(lambda: self.stackedWidget.setCurrentWidget(self.spleet))
        self.mixBtn.clicked.connect(lambda: self.stackedWidget.setCurrentWidget(self.mix))

        self.addBtnSpleet.clicked.connect(self.addSongSpleet)
        self.songListSpleet.clicked.connect(self.showSongSpleet)
        self.downSongSpleet.clicked.connect(self.downSong)
        self.playBtnSpleet.clicked.connect(lambda: self.playSong(0))
        self.prevBtnSpleet.clicked.connect(lambda: self.playSong(-1))
        self.nextBtnSpleet.clicked.connect(lambda: self.playSong(1))
        self.speedBtn.clicked.connect(self.adjustSpeed)
        self.sliderSongPlayingSpleet.valueChanged.connect(self.rewindSong)
        self.sliderVocalSpleet.valueChanged.connect(self.adjustVolume)
        self.sliderBassSpleet.valueChanged.connect(self.adjustVolume)
        self.sliderPianoSpleet.valueChanged.connect(self.adjustVolume)
        self.sliderDrumSpleet.valueChanged.connect(self.adjustVolume)
        self.sliderOtherSpleet.valueChanged.connect(self.adjustVolume)
        self.downVocalSpleet.clicked.connect(self.downSong)
        self.downBassSpleet.clicked.connect(self.downSong)
        self.downPianoSpleet.clicked.connect(self.downSong)
        self.downDrumSpleet.clicked.connect(self.downSong)
        self.downOtherSpleet.clicked.connect(self.downSong)
        self.addBtnMix.clicked.connect(self.addSongMix)
        self.playBtnMix.clicked.connect(lambda: self.playSong(0))
        self.sliderSongPlayingMix.valueChanged.connect(self.rewindSong)
        self.sliderEleMix.valueChanged.connect(self.adjustVolume)
        self.removeEleBtn.clicked.connect(self.removeEleMix)
        self.exportBtnMix.clicked.connect(self.downSong)
        self.comboBoxListMix.currentTextChanged.connect(self.addEleMix)

    # Thêm bài hát trong page Spleet
    def addSongSpleet(self):
        print("*****")
        print("Thêm bài hát trong page Spleet")

    # Hiện bài hát hiện tại ra giữa màn hình Spleet, cập nhật tên bài hát và tác giả
    # sau khi tách bài hát đấy thành các thành phần
    def showSongSpleet(self):
        print("*****")
        self.spleetSong()
        print("Hiện bài hát hiện tại ra giữa màn hình Spleet")
        print("Cập nhật tên bài hát và tác giả")

    # Tách bài hát thành các thành phần
    def spleetSong(self):
        print("Tách bài hát thành các thành phần")

    # Tạo bài hát hoàn chỉnh từ mảng tham số được truyền vào
    def combineSong(self):
        print("Tạo bài hát hoàn chỉnh từ mảng tham số được truyền vào")

    # Phát bài hát được tạo từ mảng tham số được truyền vào
    def playSong(self, index):
        print("*****")
        self.combineSong()
        if index == 0:
            print("Phát bài hát")
        elif index == -1:
            print("Phát bài hát trước")
        else:
            print("Phát bài hát sau")

    # Tải bài hát được tạo từ mảng tham số được truyền vào
    def downSong(self):
        print("*****")
        self.combineSong()
        print("Tải bài hát")

    # Điều chỉnh tốc độ bài hát được tạo từ mảng tham số được truyền vào
    def adjustSpeed(self):
        print("*****")
        self.combineSong()
        print("Điều chỉnh tốc độ bài hát")

    # Tua bài hát được tạo từ mảng tham số được truyền vào đến vị trí mong muốn
    def rewindSong(self):
        print("*****")
        self.combineSong()
        print("Tua bài hát đến vị trí mong muốn")

    # Điều chỉnh âm lượng thành phần được truyền làm tham số
    def adjustVolume(self):
        print("*****")
        print("Điều chỉnh âm lượng thành phần được truyền làm tham số")
        self.combineSong()

    # Thêm bài hát trong page Lyric
    def addSongLyric(self):
        print("*****")
        print("Thêm bài hát trong page Lyric")

    # Hiện bài hát hiện tại ra giữa màn hình Lyric
    # sau khi đã tách lyric bài hát
    def showSongLyric(self):
        print("*****")
        self.detachLyric()
        print("Hiện bài hát hiện tại ra giữa màn hình Lyric")
        print("Cập nhật tên bài hát và tác giả")

    # Tách lời bài hát
    def detachLyric(self):
        print("Tách lời bài hát")

    # Thêm bài hát trong page Mix
    # sau khi tách bài hát thành 5 thành phần
    def addSongMix(self):
        print("*****")
        self.spleetSong()
        print("Thêm bài hát trong page Mix")

    # Xóa thành phần được truyền tham số trong danh sách cần mix
    def removeEleMix(self):
        print("*****")
        print("Xóa thành phần được truyền tham số trong danh sách cần mix")

    # Thêm thành phần vào danh sách cần mix
    def addEleMix(self, value):
        if value != "None":
            print("*****")
            print("Thêm thành phần vào danh sách cần mix")
